### ISSUE TITLE
Replace model causes a ghosted and scaled copy to appear in addition to original

### ISSUE THREAD

**Issue by sidhant** [fieldOfView/Cura-MeshTools#11]
When right clicking on a model and selecting MeshTools>Replace, two issues persist:

1. The model is not _replaced_. It stays and a new copy is added to build plate. This is especially troublesome when the expectation is that MeshTools will replace the model being right clicked with contents of the loaded file and the child dependencies such as support blocker setting modifiers remain intact.
2. For the files below, I see a _second_ ghosted copy appear that is oddly scaled in Z-axis.

![Result_after_Replace](https://user-images.githubusercontent.com/680782/81040959-61ae3480-8e61-11ea-8df9-2ea1ebd1f0e5.jpg)

Files can be found here:
https://1drv.ms/u/s!AgRWV5Z66iWDj_V6Z5-x1-Fom3oEiQ?e=j5iuVh

To replicate the above screenshot:
1. Load .3mf file in Cura 4.6.1
2. Right click the "LBracket" (the taller part). MeshTools>Replace>LBracket.stl
3. Note how model is *not* replaced. Two copies of LBracket appear instead -- one correct and one scaled.

**Comment by fieldOfView** [comment]
The problem is that the "child" block also gets its mesh replaced. Because you scaled the original block, the replaced mesh also gets scaled up.

**Comment by fieldOfView** [comment]
Could you try this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/MeshTools/g1ArUVZvOb4Da3glW2zw-Jtlu6ZulqQr3LP1yHGqZm1l/MeshTools-v7.0.0-2020-05-05T09%3A14%3A35Z.curapackage?Expires=1904030078&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=JRIrfip3syYbKhzOVKsLmirTxfN9zjLBnh%2BHB0eFxdBNS8oyO%2BraXZ7MxU6WVVV%2FOm9nk1UuMioDdK%2FchasKh0yZfrzvNQ%2Baonw4kzDueCdhOAL4mnKxRfqNncTLzEJajnEvHUjqMHdlY5eyXDD4x5W0mh3aFvEkJ143NXgJuKrmm1DsImEou0FYqb8B6IqoiQFEQGL3c1rXCQ61qmhfwMNgJBXVcfhswmpZcDEgpDLB7Rtg2mWHjB4rNuBBPgQyWdtIJjaZbFuibsTK%2BIfjNB22Sln8uk6E5S8DndQTE%2Byi%2FRuC5lddyeICQ9k2%2Fh%2FmTuyZFzcNYT0N4kXjiasctw%3D%3D)? Download the file and drop it onto the Cura buildplate asif you are loading a 3d model.

**Comment by smartavionics** [comment]
Doesn't this change stop the useful behaviour of being able to replace a replicated mesh? i.e. if the user has placed 50 copies of some object on the buildplate and, subsequently, decides to replace them with a different model then now they have to replace each one separately rather than selecting all and replacing in one operation.

**Comment by smartavionics** [comment]
Isn't that capability (replace multiple objects) what was requested on slack?

**Comment by fieldOfView** [comment]
> Doesn't this stop the useful behaviour of being able to replace a replicated mesh?

It does. I'll see if I can bring it back, without causing problems with support blockers.

**Comment by sidhant** [comment]
> Could you try this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/MeshTools/g1ArUVZvOb4Da3glW2zw-Jtlu6ZulqQr3LP1yHGqZm1l/MeshTools-v7.0.0-2020-05-05T09%3A14%3A35Z.curapackage?Expires=1904030078&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=JRIrfip3syYbKhzOVKsLmirTxfN9zjLBnh%2BHB0eFxdBNS8oyO%2BraXZ7MxU6WVVV%2FOm9nk1UuMioDdK%2FchasKh0yZfrzvNQ%2Baonw4kzDueCdhOAL4mnKxRfqNncTLzEJajnEvHUjqMHdlY5eyXDD4x5W0mh3aFvEkJ143NXgJuKrmm1DsImEou0FYqb8B6IqoiQFEQGL3c1rXCQ61qmhfwMNgJBXVcfhswmpZcDEgpDLB7Rtg2mWHjB4rNuBBPgQyWdtIJjaZbFuibsTK%2BIfjNB22Sln8uk6E5S8DndQTE%2Byi%2FRuC5lddyeICQ9k2%2Fh%2FmTuyZFzcNYT0N4kXjiasctw%3D%3D)? Download the file and drop it onto the Cura buildplate asif you are loading a 3d model.

The development snapshot works perfectly as expected!

**Comment by fieldOfView** [comment]
The above commit reenables replacing multiple models at the same time, without breaking on support blockers.

**Comment by smartavionics** [comment]
Great, thanks.
