### ISSUE TITLE
Implement mesh complexity analysis

### ISSUE THREAD

**Issue by jcharaoui** [fieldOfView/Cura-MeshTools#12]
My printer is connected via USB serial connection to an Raspberry Pi device with OctoPrint.

In order to get a successful print of many models, I'll often end up to increasing the values for `Maximum Resolution` and `Maxmum Deviation`, especially on models with detailed curves. Otherwise, the serial connection isn't fast enough and buffer underruns in Marlin cause the printer to stutter. I've ruled out issues with the RPi device and USB connection. Some models, with default Cura settings, simply produce GCODE of such size and detail that it would overwhelm any serial connection.

In this context, in order to predict printability, it would be great if this plugin could expose some form of metric of mesh complexity, even if it's just a triangle count. I'm not sure if that's doable but the best would be a ratio of triangle count to total model surface.

**Comment by fieldOfView** [comment]
Just so I understand the request, why can't you keep the `Maximum Resolution` and `Maxmum Deviation` at a value where the detail will not overload the serial connection?

**Comment by jcharaoui** [comment]
@fieldOfView The effect of these two settings is a little bit unpredictable as the resulting mesh quality will be different from model to model. For example, on some models increasing those settings beyond a certain threshold will produce unacceptable distortions while it won't for others, so I'm having to always adjust to find the right balance. I don't expect this to change with this mod, but it'll help by providing some kind of baseline from which to make adjustments.

**Comment by jcharaoui** [comment]
I'll add that print speed is also a factor in this.

**Comment by jcharaoui** [comment]
Just wanted to pop by to say thank you, this feature is just what I wanted! :star2:
