### ISSUE TITLE
Cut a model on one plane

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeshTools#13]
One function wich could be usefull to add in this plugin : the possibility to cut the model on one plane.

trimesh.intersections.slice_mesh_plane ?

**Comment by fieldOfView** [comment]
> trimesh.intersections.slice_mesh_plane

It is a bit harder than that; the model also needs a "cap" to be watertight again.

**Comment by 5axes** [comment]
If the model is not too complex (perhap's limited to convex model) can we expect to fill the hole with: trimesh.repair.fill_holes ?

**Comment by fieldOfView** [comment]
Only if there are no holes in the cross-section.

**Comment by fieldOfView** [comment]
This has been implemented by someone else in a dedicated plugin:
https://hci.rwth-aachen.de/m3-autoparter

**Comment by 5axes** [comment]
Much more than expected .. thanks for the link
