### ISSUE TITLE
Cura becomes unresponsive when Fix model Normals is selected

### ISSUE THREAD

**Issue by dubbsd** [fieldOfView/Cura-MeshTools#14]
when I click on fix model normals  Cura becomes unresponsive.
I am running Windows 10 64bit.
and have 16gb of ram so it is not a ram problem

**Comment by fieldOfView** [comment]
Does this happen for all models? If not, could you share a model this happens for?

What version of Cura do you use?

**Comment by dubbsd** [comment]
it happens with all models i do from Itslitho.com
I am using Cura version 4.6.1

[jean-I-Gray.zip](https://github.com/fieldOfView/Cura-MeshTools/files/4919371/jean-I-Gray.zip)

**Comment by fieldOfView** [comment]
I tested with the model. Cura does not crash, but fixing the normals of 2 million faces takes a long time. On my computer it took a good couple of minutes. During this time Cura becomes "unresponsive" but there is little I can do about that.

In this model, there is nothing wrong with the normals; they don't need fixing.
