### ISSUE TITLE
getLocalTransformation() got an unexpected keyword argument 'copy'

### ISSUE THREAD

**Issue by nallath** [fieldOfView/Cura-MeshTools#15]
The copy parameter was added in 4.7, so it's crashing in 4.6.*

https://sentry.io/share/issue/89a4b53d4bfe49ef9b11af281680aa2c/

In this case, it's probably best to just remove the argument (the default is copy = True anyway).

**Comment by fieldOfView** [comment]
Huh, interesting. I already "fixed" this a month ago (https://github.com/fieldOfView/Cura-MeshTools/commit/3a3544a7392b5f31f902080d774909b285ba6821#diff-d216341f998807ae57a14b197dc557a8R471), but had not gotten around to making a new release and forgot all about it.
