### ISSUE TITLE
Replace command broken

### ISSUE THREAD

**Issue by JRTrudel** [fieldOfView/Cura-MeshTools#16]
When reopening project and trying to replace an object the original one remain and the new one is loaded over it.    They become one object.

![image](https://user-images.githubusercontent.com/29367817/94168991-38b42d80-fe5c-11ea-87f5-eb34b9b7113d.png)

**Comment by fieldOfView** [comment]
This could be happening because the model is grouped.

Could you attach the project, so I can try to reproduce the issue?

**Comment by JRTrudel** [comment]
here is my project
https://drive.google.com/file/d/182AufvxrR5l1ENFzwZT8W8yr7li_Z8aZ/view?usp=sharing

**Comment by fieldOfView** [comment]
For now I have "fixed" this by not allowing the "Replace model..." function to work on groups. You can replace the model itself by either ungrouping the group, or by ctrl-clicking the actual mesh you want to replace, thus selecting only the mesh and not the group.

**Comment by JRTrudel** [comment]
Thank you!!!!
