### ISSUE TITLE
Rotate uses original center when models are split apart

### ISSUE THREAD

**Issue by KenLucke** [fieldOfView/Cura-MeshTools#17]
This is a reminder, as requested, to add a function to optionally reset the origin of a sub-model after splitting, per Cura discussion here:

https://github.com/Ultimaker/Cura/issues/8810

**Comment by fieldOfView** [comment]
> 
> 
> **Application version**
> 4.8, but this has been ongoing (not a new issue, I just remembered it because it cropped up again in a project)
> 
> **Platform**
> Mac OSX 15.5.7
> 
From the original report:

> **Printer**
> N/A
> 
> **Reproduction steps**
> 
> 1. Import a model capable of being broken into sub-models (the larger the separation between various parts, the more apparent will be the results)
> 
> 2. Use "**Mesh Tools > Split Models Into Parts**" to split the model
> 
> 3. Try to rotate one of new sub-parts.
> 
> 
> **Screenshot(s)**
> 
> **Actual results**
> The part will rotate around what was the _original_ center of of the whole model, rather than around its new individual center. This also affects the "**Lay Flat**" and "**Select Face to Align to the Build Plate**" options.
> 
> **Expected results**
> Each individual part (model) after a split should have its own individual center, just as if they had been imported individually.
> 
> **Project file**
> N/A
> 
> **Log file**
> N/A
> 
> **Additional information**

My reply:
> Mesh Tools keeps the original origin of the compound mesh, so it is possible to "merge" individual parts back together (eg after assigning them to different extruders) and having them "snap together" in their original position relative to eachother. If the Mesh Tools plugin were to reset the origin to the center of the sub-model, the position relative to the other sub-models would be lost and it would not longer be possible to merge them.

**Comment by fieldOfView** [comment]
In the next release of the plugin, there will be a function to "Reset origin to center of mesh". This fixes rotation, but ruins any chance of merging the models back together with their original relative positions. 

I'll keep this issue open until the next version is available in the Marketplace.
