### ISSUE TITLE
Cura crashed when I used Mesh Tools | Replace Model

### ISSUE THREAD

**Issue by githubluis** [fieldOfView/Cura-MeshTools#19]
Cura crashed when I used Mesh Tools | Replace Model with a .3MF file (attached .zip) I exported out of Solidworks 2018 SP 5.0. But an STL file works. (also attached)

[Masking tool STL.zip](https://github.com/fieldOfView/Cura-MeshTools/files/6070230/Masking.tool.STL.zip)
[Masking tool.zip](https://github.com/fieldOfView/Cura-MeshTools/files/6070212/Masking.tool.zip)
[Logs.txt](https://github.com/fieldOfView/Cura-MeshTools/files/6070187/Logs.txt)
[Error Traceback.txt](https://github.com/fieldOfView/Cura-MeshTools/files/6070188/Error.Traceback.txt)
![System Info](https://user-images.githubusercontent.com/638403/109681145-ccdc9c00-7b42-11eb-8e5a-2a21a18bcf9f.png)

**Comment by fieldOfView** [comment]
The crash should be fixed in the above commit. I'll keep this issue open until a new version is available in the Marketplace.
