### ISSUE TITLE
Split into parts deletes support blockers

### ISSUE THREAD

**Issue by BagelOrb** [fieldOfView/Cura-MeshTools#2]
Perhaps this is something you aren't really willing to spend time on, but the split into parts functionality now deletes support blockers on the original model.

PS: I'm actually not sure whether the split into parts works on all models on the build plate or only the selected ones.

**Comment by fieldOfView** [comment]
Sounds fixable. Not as quickly as #1, but give it some time. 

All the MeshTools should work on the selected objects only. 

Support Blockers are parented to a normal mesh, and the normal mesh gets deleted. The tricky bit is going to be to decide whick of the newly created models to use as the parent.

**Comment by BagelOrb** [comment]
It doesn't really matter, just pick the first for now.

In my case I was using one blocker for all parts at the same time.

Implementing the functionality that you choose the closest mesh might be
too difficult, so you could leave that for an indefinite future
improvement. ;)

On 8 Nov 2018 6:12 p.m., "Aldo Hoeben" <notifications@github.com> wrote:

Sounds fixable. Not as quickly as #1
<https://github.com/fieldOfView/MeshTools/issues/1>, but give it some time.

All the MeshTools should work on the selected objects only.

Support Blockers are parented to a normal mesh, and the normal mesh gets
deleted. The tricky bit is going to be to decide whick of the newly created
models to use as the parent.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fieldOfView/MeshTools/issues/2#issuecomment-437081281>,
or mute the thread

**Comment by fieldOfView** [comment]
> It doesn't really matter, just pick the first for now.

Ofcourse it does. If your compound model contains two bodies (A and B), and you add a support blocker to body B. Then split the model and the support blocker gets parented to what is now model A, though it is still in place with model B. Then you move model A. This then creates a lot of confusion, and you'll be back here telling me I did it wrong ;-)

**Comment by BagelOrb** [comment]
Uhm yeah you're right.

**Comment by fieldOfView** [comment]
@BagelOrb, could you test f9ad8c5?

**Comment by fieldOfView** [comment]
Now available in the ~Toolbox~Marketplace
