### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by KenLucke** [fieldOfView/Cura-MeshTools#21]
While looking for a changelog or similar, I accidentally forked this.  I don't want a fork :).  How the hell do I delete "my" fork repository?  I can't find a "delete" option anywhere.

**Comment by fieldOfView** [comment]
Go to https://github.com/KenLucke/Cura-MeshTools/settings, and scroll all the way down.

**Comment by KenLucke** [comment]
Thank you!
