### ISSUE TITLE
PLEASE ADD LINK TO PLUGIN DOWNLOAD

### ISSUE THREAD

**Issue by AaryanL** [fieldOfView/Cura-MeshTools#22]
I don't understand how to download the plugin.
Thank you.

**Comment by fieldOfView** [comment]
There is no need to scream. Plugins are installed via the "Marketplace" in Cura, which is accessible with a button in the top right of the window.

**Comment by AaryanL** [comment]
Just forgot to switch CapsL off.
I found already, and closed the issue.
Thank you for the answer.

**Comment by AaryanL** [comment]
It should be deleted in fact.
