### ISSUE TITLE
Models incorrectly marked as non-manifold

### ISSUE THREAD

**Issue by nallath** [fieldOfView/Cura-MeshTools#23]
I've found a weird issue and ironically, I only found it because I was working on a plugin myself (https://github.com/nallath/ModelCutter)

Since I also want to use Trimesh, but then to cut objects ( trimesh.intersections.slice_mesh_plane, but with the cap enabled), I looked at your plugin to get some hints as to what would be the best way to convert cura meshdata to trimesh.

When using your version, no matter what I did, I would get warnings that the mesh was non-manifold, thus resulting in the cutting not being possible. But in my very simple script, the same model would _not_ be seen as non-manifold...

So after a lot of very frustrated debugging and pretty much trying every single fixing algorithm that trimesh has, I found out that the normals are at fault here. 

So basicly if you use `return trimesh.base.Trimesh(vertices=mesh_data.getVertices(), faces=indices, vertex_normals=mesh_data.getNormals())`, the mesh is almost always seen as non-manifold.

If you use return `trimesh.base.Trimesh(vertices=mesh_data.getVertices(), faces=indices)`, which is what the stl loader of trimesh also does, it does work.

**Comment by fieldOfView** [comment]
Thanks, I'll have a quick test and see. 

I think Cura should throw out normals supplied in models anyway. "Smooth" normals are misleading (the sliced model will not be smoothed in the same way), and inverted or broken normals are confusing (especially with the red overhang visualisation).

**Comment by nallath** [comment]
The strange thing is, Cura doesn't even read the normals from the STL, since it doesn't even contain them. I've looked at the data and the normals look to be correct. I can't really put my finger on what is the issue though.
