### ISSUE TITLE
Any way to disable to "non watertight" notification ?

### ISSUE THREAD

**Issue by mistic100** [fieldOfView/Cura-MeshTools#24]
Hello

I would like to be able to use this plugin without constantly having stacked notifications about non watertight models (which most of the time is not a problem because Cura mesh fixes works very well).

Or if not feasible, could the notification be cleared when the model is removed from the build plate ?

**Comment by fieldOfView** [comment]
See `Extensions -> MeshTools -> Mesh Tools settings...` and uncheck the `Check models on load` option.

**Comment by mistic100** [comment]
Okay, my bad, I was searching for options from the marketplace window.

Thank you
