### ISSUE TITLE
Feature: Methods to check to inspect displacements between STL mesh and GCode render.

### ISSUE THREAD

**Issue by alpha358** [fieldOfView/Cura-MeshTools#25]
Hi,
are there any tools that can display the largest surface displacements caused by the slicer?
(e.g. due to rounding the geometry to multiples of the printer nozzle diameter)

**Comment by fieldOfView** [comment]
> are there any tools that can display the largest surface displacements caused by the slicer?

That sort of calculation is a bit beyond the scope of this plugin.

> (e.g. due to rounding the geometry to multiples of the printer nozzle diameter)

You may want to look in to the "Arachne" previews, of what will become Cura 5.0:
https://support.ultimaker.com/hc/en-us/articles/360018439500-Ultimaker-Cura-Arachne-engine-beta-version

**Comment by fieldOfView** [comment]
Sorry, I meant this Arachne link:
https://ultimaker.com/learn/3d-printing-revolution-continues-second-beta-for-ultimaker-cura-arachne

**Comment by alpha358** [comment]
Thank you very much! This is very usefull.
