### ISSUE TITLE
Cura fails to start, dead processes still listed by task manager #15182

### ISSUE THREAD

**Issue by kiniad** [fieldOfView/Cura-MeshTools#35]
See: https://github.com/Ultimaker/Cura/issues/15182

It turns out, that this new plugin version 3.7.1 prevents my cura from starting up.
The blue start window from cura shows the last message "Loading UI...", dissapears, and nothing more happens.

Without the MeshTools 3.7.1 all is working well in Cura again.

**Comment by Randomblock1** [comment]
Can confirm this is an issue, with this plugin Cura opens successfully only about 30% of the time

On MacOS Cura is just active in the Dock with no actual windows open

**Comment by GregValiant** [comment]
Me too.
It started immediately after updating Mesh Tools so I knew what had caused it.  Uninstalling Mesh Tools was tough since Cura wouldn't start.  Uninstalling it fixed the problem.

**Comment by fieldOfView** [comment]
Thanks for reporting. I'm looking in to it. The previous version is still available here:
https://github.com/fieldOfView/Cura-MeshTools/releases/tag/v3.7.0

**Comment by fieldOfView** [comment]
Strange, the v3.7.1 update is a fairly minor change from v3.7.0. Here are all the code-changes:
https://github.com/fieldOfView/Cura-MeshTools/compare/v3.7.0...v3.7.1

It would be really nice if you could confirm that 3.7.0 does not exhibits the problem.
https://github.com/fieldOfView/Cura-MeshTools/releases/tag/v3.7.0
Download the "Cura5.0.curapackage " and drop the file onto the Cura buildplate as if you were opening a 3d model.

**Comment by fieldOfView** [comment]
I have (temporarily) removed the plugin from the Marketplace, so users are no longer told to update to this problematic version.
See #36

**Comment by fieldOfView** [comment]
Please help test this easter-morning hotfix:
https://github.com/fieldOfView/Cura-MeshTools/releases/tag/v3.7.2-DEV

**Comment by Randomblock1** [comment]
The hotfix works, Cura now opens perfectly fine

**Comment by fieldOfView** [comment]
Thanks for the quick test! 

Unfortunately it is going to take a little while before a new version of the plugin is going to be available in the Marketplace. Any update is tested before it is published, and I assume the Cura team are enjoying Easter.

**Comment by GregValiant** [comment]
+1 The fix seems fine.

FYI...I heard from the Tooth Fairy that the Easter Bunny is a myth.
Happy Easter anyway.

**Comment by fieldOfView** [comment]
Version 3.7.2 is now available in the Marketplace, fixing this issue.
