### ISSUE TITLE
MeshTools 3.7.1 caused issues opening Cura

### ISSUE THREAD

**Issue by fieldOfView** [fieldOfView/Cura-MeshTools#36]
A new version of the MeshTools plugin (3.7.1) was published to the Marketplace last week. I was made aware of an issue launching Cura with this new version of the plugin installed. In order to prevent users from installing this version and from being unable to launch Cura, I have withdrawn the release from the Marketplace. Unfortunately this means that the plugin is currently entirely unavailable from the Marketplace, since I can not simply put back the previous release.

The problem is that the Cura 5.3 window does not open after the loading of the application is complete. Cura will continue to run, but no visible user interface shows. This does not happen on all launches; some users report Cura opening 30% of the time. Other users may see the issue more or less frequently. The problematic version of the plugin was extensively tested before release, not just by me but also by the UltiMaker Cura team. I am sorry this slipped through.

If you installed the 3.7.1 release of the plugin, and you are affected by the issue, here are some things you can do.

MeshTools 3.7.2 has been released to the Marketplace. If you can still open Cura, you can update the MeshTools plugin via the Marketplace.

If you are unable to open Cura, the easiest thing to so is to first remove the plugin.

Locate the plugins folder in the Cura configuration folder:

Windows:
`%APPDATA%\cura\<CuraVersion>\plugins`
or
`C:\Users\<your username>\AppData\Roaming\cura\<CuraVersion>\plugins`

Linux
`~/.local/share/cura/<CuraVersion>/plugins`

Mac OS
`~/Library/Application Support/cura/<CuraVersion>/plugins`

To remove the plugin entirely, it remove the entire MeshTools folder.

You should now be able to run Cura again, and you can install the 3.7.2 of the MeshTools plugin via the Marketplace.

**Comment by fieldOfView** [comment]
MeshTools release 3.7.2-DEV fixes the issue. See https://github.com/fieldOfView/Cura-MeshTools/releases/tag/v3.7.2-DEV

**Comment by nallath** [comment]
I've approved the version in the marketplace!

**Comment by fieldOfView** [comment]
Thanks for the superquick review!

I'll leave this issue open for a while, until the dust settles.
