### ISSUE TITLE
Split into parts drops all parts to the plate

### ISSUE THREAD

**Issue by buddybu** [fieldOfView/Cura-MeshTools#37]
![image](https://github.com/fieldOfView/Cura-MeshTools/assets/6501723/74f02704-8f2c-4b5b-9773-da70328553fc)

I was loading a miniature for 3d printing and I wanted to explicitly print parts of it in a different color, so I tried to split the mesh, but the model seemed to fall completely apart and all the parts are now just laying in a pile on the plate.  

![image](https://github.com/fieldOfView/Cura-MeshTools/assets/6501723/049f0988-e1fc-4d5e-a0b8-a74832b74691)

I am running mesh tools 3.6.0

**Comment by fieldOfView** [comment]
You could turn off the "Automatically drop models to the build plate" option in the General preferences in Cura to prevent this from happening. Or you can select all split models and use the "Merge models" function in Cura to move them back into their original relative position. You can then still select and manipulate each individual model within the merged group by Ctrl-clicking.

This is not a defect of this plugin, but how Cura works.
