### ISSUE TITLE
Take me to X-ray view

### ISSUE THREAD

**Issue by BagelOrb** [fieldOfView/Cura-MeshTools#5]
Cura 4.0.0

I have:
- Mesh tools installed
- Side bar plugin installed
- almost all of your plugin installed ;)

1. Load a broken mesh
2. Get the message to check out X-ray view
3. Click on [Show X-ray view]
4. nothing happens

Expected: switch to X-ray!

**Comment by fieldOfView** [comment]
This is now working correctly on the master branch, in combination with the master branch of the SidebarGUI plugin.
