### ISSUE TITLE
Bad object locations after split

### ISSUE THREAD

**Issue by GMagician** [fieldOfView/Cura-MeshTools#7]
It seems that mesh tools doesn't handle correctly objects position in a cura project.
Once project is reloaded, positions are wrong.

More details at https://github.com/Ultimaker/Cura/issues/6129

**Comment by GMagician** [comment]
This has been seen in Cura 4.3.0

**Comment by fieldOfView** [comment]
> Once project is reloaded, positions are wrong.

That makes it a Cura issue. The state after loading a Cura project should be the state when saving the Cura project. I'll see what I can do fixing this in Cura, but it is not something this plugin is doing wrong.

Also see this comment: https://github.com/fieldOfView/Cura-MeshTools/pull/8#issuecomment-526544282

**Comment by GMagician** [comment]
Sorry just see now...

> That makes it a Cura issue.

Posted on cura repository and they told me it was a mesh bug, that's funny.

Thanks for taking a look at it
